### ISSUE TITLE
"The user does not exist" sometimes appears after updating username

### ISSUE THREAD

**Issue by ztsai** [cofacts/rumors-site#386]
user is redirected to their new profile page after updating their username, however, depending on the traffic, sometimes it would be 404'ed.

**Comment by MrOrz** [comment]
This is probably because when we query by `slug` it is invoking Search API. If elasticsearch database have not indexed such `slug` we will meet this error.

On staging & production, I forgot not apply `keyword` type to `slug` (see https://github.com/cofacts/rumors-site/issues/399#issuecomment-788004931 ). In this case Elasticsearch may take longer to index because it's dealing with full text indexes rather than keywords.

Hopefully after we fix the index issue, the redirect bug would go away; if not, we may need to consider removing the automatic redirect after the user updated their username. In this case, the user can still refresh the page manually if they want to.

**Comment by MrOrz** [comment]
As cofacts/rumors-db#53 merges, this should be fixed. Close for now.
