### ISSUE TITLE
Category label is not updated after adding one category

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-site#481]
After adding a category, currently there is no any visual feedback that tells the user that the category is added.

![no-response](https://user-images.githubusercontent.com/108608/162559676-022d4169-ba14-4525-a804-47b988fd6df0.gif)

Current workaround: refresh the whole page
Expected: UI should show that the category is added immediately (or shortly after API response)

**Comment by marcussfu** [comment]
I want to fix the issue.

**Comment by jiru** [comment]
Working on this.
I think this bug was introduced by cf550a0c.
Console shows this error:
```
Invariant Violation: Can't find field articleCategories on object {
  "id": "91m530brhhfo",
  "text": ...
  ...
  "articleCategories({\"statuses\":[\"NORMAL\"]})": [
    {
      "type": "id",
      "generated": false,
      "id": "ArticleCategory:91m530brhhfo__oT2o7nEBrIRcahlYKQoM",
      "typename": "ArticleCategory"
    }
  ],
  "stats": [
    ...
  ],
  "user": {
    ...
  }
}
```
`readFragment()` (called in `components/ArticleCategories/CategoryOption.js`) throws an error because the key of the categories array is `articleCategories({"statuses":["NORMAL"]})` instead of the expected `articleCategories`.

To work around the problem, I suggest we always fetch all categories (remove statuses filter in query) and instead we change the display of categories according to whether the user is blocked and category status equals `BLOCKED`.

**Comment by jiru** [comment]
Eventually I found a simpler way to solve the problem; please have look at my PR :slightly_smiling_face:
